-- Re-carga las 75 tarjetas del widget original.
-- Idempotente: solo inserta las que no existen ya (clave: word).
-- No borra ni modifica tus tarjetas custom ni el progreso.

insert into public.cards (word, meaning, example, module)
select v.word, v.meaning, v.example, v.module
from (values
  ('Stuff', 'Cosas / material / sustancia', 'Where''s my stuff? I thought I left it here.', 'SEMANA 1'),
  ('You guys', 'Vosotros / ustedes (coloquial)', 'How are you guys? Are you guys coming?', 'SEMANA 1'),
  ('Guy', 'Tipo / tío / hombre (coloquial)', 'He''s a nice guy, isn''t he?', 'SEMANA 1'),
  ('To deal with', 'Lidiar con / ocuparse de algo', 'We have to deal with it. I don''t want to deal with him.', 'SEMANA 2'),
  ('What''s the deal?', '¿Qué pasa? / ¿Qué ocurre?', 'What''s the deal? Here''s the deal…', 'SEMANA 2'),
  ('No big deal', 'No es para tanto / no hay problema', 'No big deal! Don''t worry about it.', 'SEMANA 2'),
  ('The real deal', 'Lo auténtico / el crack / lo mejor de verdad', 'This guy''s the real deal!', 'SEMANA 2'),
  ('A great deal of', 'Una gran cantidad de', 'He''s causing a great deal of problems.', 'SEMANA 2'),
  ('To blow your mind', 'Dejarte alucinado / sorprenderte muchísimo', 'This new technology is going to blow your mind.', 'SEMANA 2'),
  ('To blow you away', 'Dejarte muy impresionado / sorprenderte', 'I was blown away by the new technology.', 'SEMANA 2'),
  ('Hang in there', 'Aguanta / sé fuerte / no te rindas', 'Hang in there, it''s gonna be okay.', 'SEMANA 2'),
  ('You rock / This rocks', 'Eres increíble / esto mola / eres la leche', 'You rock man! You did a great job!', 'SEMANA 2'),
  ('Flap T', 'La T/D que suena como "r" española suave (entre vocales)', 'Party, city, water, better, meeting — la T entre vocales.', 'SEMANA 1'),
  ('Wanna', 'Want to — querer hacer algo (coloquial oral)', 'Do you wanna come? I wanna go there.', 'SEMANA 2'),
  ('Gonna', 'Going to — ir a hacer algo (coloquial oral)', 'It''s gonna be fine. Everything''s gonna work out.', 'SEMANA 2'),
  ('However', 'Sin embargo (conecta ideas opuestas, formal)', 'It was a tough game. However, we managed to win.', 'SEMANA 1'),
  ('Nevertheless', 'Sin embargo / aun así (más formal que however)', 'He works a lot. Nevertheless, he doesn''t have money.', 'SEMANA 1'),
  ('Even though / Although', 'Aunque / a pesar de que', 'Even though I''m tired, I still want to go out.', 'SEMANA 1'),
  ('On the one hand… on the other hand', 'Por un lado… por otro lado', 'On the one hand it''s useful. On the other hand it''s expensive.', 'SEMANA 1'),
  ('Whereas', 'Mientras que (contraste directo entre dos cosas)', 'This movie is great, whereas that one is boring.', 'SEMANA 1'),
  ('Instead of / Rather than', 'En lugar de / en vez de', 'Instead of texting her, why don''t you call her?', 'SEMANA 1'),
  ('Despite / In spite of', 'A pesar de / pese a', 'In spite of being insulted, he kept his temper.', 'SEMANA 1'),
  ('Unless', 'A menos que / a no ser que', 'You don''t need to go unless you want to.', 'SEMANA 1'),
  ('Yet', 'Aún así (contraste, más literario que however)', 'It''s a small car, yet it''s surprisingly wide.', 'SEMANA 1'),
  ('Otherwise', 'O si no / de lo contrario', 'We could go now. Otherwise, we could go in the evening.', 'SEMANA 1'),
  ('On the contrary', 'Todo lo contrario / por el contrario', 'Did you say she was nice? On the contrary, she''s really mean.', 'SEMANA 1'),
  ('Nonetheless', 'Sin embargo / no obstante (formal, escrito)', 'The results were mixed. Nonetheless, the project moved forward.', 'SEMANA 1'),
  ('Undoubtedly', 'Sin duda / indudablemente', 'Undoubtedly, this restaurant is the best in town.', 'SEMANA 2'),
  ('Indeed', 'De hecho / ciertamente / sí que (énfasis)', 'Did you enjoy the film? Yes, indeed.', 'SEMANA 2'),
  ('Especially', 'Especialmente / sobre todo', 'This is hard, especially if you''re tired.', 'SEMANA 2'),
  ('Clearly / Obviously', 'Claramente / obviamente', 'Clearly, this car is bigger than that one.', 'SEMANA 2'),
  ('In particular', 'En particular / concretamente', 'I like these cars, in particular this one.', 'SEMANA 2'),
  ('Pity', 'Pena / lástima', 'What a pity you can''t come to the meeting.', 'SEMANA 1'),
  ('Notice', 'Darse cuenta / notar', 'Did you notice the change in strategy?', 'SEMANA 1'),
  ('Matter', 'Asunto / tema / importar', 'We talked about thirty different matters at the meeting.', 'SEMANA 1'),
  ('Settle', 'Asentarse / establecerse / resolver', 'Her daughter got settled in Seattle.', 'SEMANA 1'),
  ('Attitude', 'Actitud', 'His attitude toward innovation changed everything.', 'SEMANA 1'),
  ('Gratitude', 'Gratitud / agradecimiento', 'I''d like to express my gratitude for your support.', 'SEMANA 1'),
  ('Hesitate', 'Dudar / vacilar', 'Don''t hesitate to contact me if you need anything.', 'SEMANA 1'),
  ('Pretty', 'Bastante / muy (adverbio) / guapo,a (adjetivo)', 'That''s a pretty good deal for the company.', 'SEMANA 1'),
  ('Better', 'Mejor', 'We need a better approach to this problem.', 'SEMANA 1'),
  ('Bitter', 'Amargo / resentido', 'He was bitter about losing the contract.', 'SEMANA 1'),
  ('Waiter', 'Camarero', 'The waiter recommended the local fish.', 'SEMANA 1'),
  ('Politician', 'Político (persona)', 'The politician avoided the question completely.', 'SEMANA 1'),
  ('Narrow', 'Estrecho / limitado', 'That narrow arrow went into the apple.', 'SEMANA 2'),
  ('Laugh', 'Reír / risa', 'He laughed at the idea at first, then approved it.', 'SEMANA 2'),
  ('Fast', 'Rápido / rápidamente', 'We need to move fast on this project.', 'SEMANA 2'),
  ('Ask', 'Preguntar / pedir', 'Don''t hesitate to ask if you need clarification.', 'SEMANA 2'),
  ('Angry', 'Enfadado / enojado', 'The client was angry about the delay.', 'SEMANA 2'),
  ('Language', 'Idioma / lenguaje', 'Body language matters as much as words in a pitch.', 'SEMANA 2'),
  ('Bank', 'Banco / banca', 'The bank approved the funding for the project.', 'SEMANA 2'),
  ('Thanks', 'Gracias (informal)', 'Thanks for joining the call on short notice.', 'SEMANA 2'),
  ('Funny', 'Gracioso / curioso / extraño', 'It''s funny how the market shifted overnight.', 'SEMANA 2'),
  ('Know', 'Saber / conocer', 'I know this market better than anyone.', 'SEMANA 2'),
  ('Near', 'Cerca / próximo', 'We''re near a breakthrough with this technology.', 'SEMANA 2'),
  ('Noon', 'Mediodía', 'Let''s schedule the call for noon.', 'SEMANA 2'),
  ('Pneumonia', 'Neumonía', 'He missed the conference due to pneumonia.', 'SEMANA 2'),
  ('Treasure', 'Tesoro / valorar mucho', 'This data is a real treasure for our analysis.', 'SEMANA 2'),
  ('Leisure', 'Tiempo libre / ocio', 'I went to Germany for leisure, not for business.', 'SEMANA 2'),
  ('Casual', 'Informal / relajado', 'It''s a casual dinner so I''m gonna wear casual clothes.', 'SEMANA 2'),
  ('Collision', 'Colisión / choque', 'The two strategies led to a direct collision.', 'SEMANA 2'),
  ('Version', 'Versión', 'Please send me the latest version of the report.', 'SEMANA 2'),
  ('Conclusion', 'Conclusión / cierre', 'In conclusion, I wouldn''t do it.', 'SEMANA 2'),
  ('Unusual', 'Inusual / poco común', 'That was an unusual approach to the problem.', 'SEMANA 2'),
  ('Usually', 'Normalmente / habitualmente', 'I usually prepare the agenda the night before.', 'SEMANA 2'),
  ('Exposure', 'Exposición / visibilidad', 'This role gives me great exposure to the board.', 'SEMANA 2'),
  ('Envision', 'Imaginar / vislumbrar / contemplar el futuro', 'Let''s envision a bright future for our business.', 'SEMANA 2'),
  ('Conversion', 'Conversión (negocio / dato)', 'The conversion rate of this website is 2%.', 'SEMANA 2'),
  ('Seizure', 'Convulsión / incautación', 'Exposure to flashing lights can trigger seizures.', 'SEMANA 2'),
  ('To mumble', 'Balbucear / hablar entre dientes / mascullar', 'Stop mumbling and speak clearly!', 'SEMANA 2'),
  ('To babble', 'Balbucear / hablar sin parar sin decir nada', 'The baby was babbling in his crib.', 'SEMANA 2'),
  ('Bubble', 'Burbuja', 'The dot-com bubble burst in 2000.', 'SEMANA 2'),
  ('Rubber', 'Goma / caucho', 'The rubber seal on the device failed.', 'SEMANA 2'),
  ('Bug', 'Bicho / error de software / espiar', 'There''s a bug in the system we need to fix.', 'SEMANA 2'),
  ('Bumblebee', 'Abejorro', 'Bob saw a bumblebee on the doorknob.', 'SEMANA 2')
) as v(word, meaning, example, module)
where not exists (select 1 from public.cards c where c.word = v.word);

-- Comprobación: cuántas tarjetas tienes ahora
select count(*) as total, count(distinct module) as modulos from public.cards;
